config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::extensions('csv');

Router::scope('/', function (RouteBuilder $routes) {
    $routes->setExtensions(['json', 'csv']);
    $routes->resources('Documents');
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Dashboard', 'action' => 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);


});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/UsersTable.php
<?php

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Users Model
 *
 * @property \App\Model\Table\ContractsTable|\Cake\ORM\Association\BelongsTo $Contracts
 * @property \App\Model\Table\ConfigurationsTable|\Cake\ORM\Association\HasMany $Configurations
 * @property \App\Model\Table\ExtractsTable|\Cake\ORM\Association\HasMany $Extracts
 *
 * @method \App\Model\Entity\User get($primaryKey, $options = [])
 * @method \App\Model\Entity\User newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\User[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\User|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\User patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\User[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\User findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class UsersTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('users');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Contracts', [
            'foreignKey' => 'contract_id'
        ]);
        $this->hasMany('Configurations', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('Extracts', [
            'foreignKey' => 'user_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('first_name')
            ->requirePresence('first_name', 'create')
            ->notEmpty('first_name');

        $validator
            ->scalar('last_name')
            ->allowEmpty('last_name');

        $validator
            ->scalar('username')
            ->requirePresence('username', 'create')
            ->notEmpty('username')
            ->add('username', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);

        $validator
            ->scalar('password')
            ->requirePresence('password', 'create')
            ->notEmpty('password');

        $validator
            ->allowEmpty('access_admin');

        $validator
            ->allowEmpty('access_client')
            ->boolean('access_client');

        $validator
            ->allowEmpty('active')
            ->boolean('active');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['username']));

        return $rules;
    }

    public function findAuth(\Cake\ORM\Query $query, array $options)
    {
        $query
            ->where(['Users.active' => 1]);
        return $query;
    }

}

src/Controller/AccountController.php
<?php

namespace App\Controller;

use App\Controller\AppController;
use App\Model\Table\ExtractsTable;
use App\Model\Table\UsersTable;

/**
 * Users Controller
 *
 * @property \App\Model\Table\UsersTable $Users
 * @method \App\Model\Entity\User[] paginate($object = null, array $settings = [])
 * @property ExtractsTable $Extracts
 */
class AccountController extends AppController
{


    public function initialize()
    {
        parent::initialize();
        $this->Auth->allow(['login', 'add']);
        $this->loadComponent('Search.Prg', [
            'actions' => ['index']
        ]);
        $this->set('titlePage', 'Usuários');

        $this->loadModel('Users');
        $this->loadModel('Extracts');
    }

    /**
     * View method
     *
     * @param string|null $id User id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function extract()
    {

        $conditions = [
            'user_id' => $this->Auth->user('id')
        ];

        // Filtro Extrato
        $e_year = ($this->request->getQuery('year')) ? $this->request->getQuery('year') : date('Y');
        $e_month = ($this->request->getQuery('month')) ? $this->request->getQuery('month') : date('m');

        if ($e_year != 'all') {
            $conditions['YEAR(Extracts.date)'] = $e_year;
        }

        if ($e_month != 'all') {
            $conditions['MONTH(Extracts.date)'] = $e_month;
        }


        $extracts = $this->paginate(
            $this->Extracts->find('all')
                ->where($conditions));

        // BTC
        $sumExtractBtc = $this->Extracts->find('all')->where(['user_id' => $this->Auth->user('id')]);
        $sumExtractBtc = $sumExtractBtc->select(['sum' => $sumExtractBtc->func()->sum('cripto_coin')])->first();
        // RETIRADAS
        $sumExitBtc = $this->Extracts->find('all')->where(['user_id' => $this->Auth->user('id'), 'type' => 'WITHDRAWAL']);
        $sumExitBtc = $sumExitBtc->select(['sum' => $sumExitBtc->func()->sum('cripto_coin')])->first();
        // Operções
        $sumOperationBtc = $this->Extracts->find('all')->where(['user_id' => $this->Auth->user('id'), 'type IN' => ['OPERATION_EXIT', 'OPERATION_ENTRY']]);
        $sumOperationBtc = $sumOperationBtc->select(['sum' => $sumOperationBtc->func()->sum('cripto_coin')])->first();
        // REAL
        $sumExtractReal = $this->Extracts->find('all')->where(['user_id' => $this->Auth->user('id')]);
        $sumExtractReal = $sumExtractReal->select(['sum' => $sumExtractReal->func()->sum('real_coin')])->first();

        $user = $this->Extracts->Users->get($this->Auth->user('id'));
        $this->set(compact('extracts', 'user', 'sumExtractBtc', 'sumExtractReal', 'e_year', 'e_month', 'sumExitBtc', 'sumOperationBtc'));
        $this->set('_serialize', ['extracts']);
    }

    /**
     * View method
     *
     * @param string|null $id User id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function information()
    {
        $user = $this->Users->get($this->Auth->user('id'), [
            'contain' => ['Contracts', 'Configurations', 'Extracts'],
            'conditions' => [
                'access_client' => true
            ]
        ]);

        $this->set('user', $user);
        $this->set('_serialize', ['user']);
    }
}

src/Template/Account/add.ctp
<?= $this->element('header', [
    'title' => 'Clientes',
    'subtitle' => 'Adicionar'
])
?>

<section class="page-content container-fluid">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card">
                <!-- /.card-header -->
                <!-- form start -->
                <?= $this->Form->create($user, array('role' => 'form')) ?>
                <div class="card-body">
                    <?php
                    echo $this->Form->input('first_name', ['label' => 'Primeiro Nome']);
                    echo $this->Form->input('last_name', ['label' => 'Sobrenome']);

                    echo $this->Form->input('access_admin', ['value' => false, 'type' => 'hidden']);
                    echo $this->Form->input('access_client', ['value' => true, 'type' => 'hidden']);
                    echo $this->Form->input('active', ['value' => true, 'type' => 'hidden']);
                    echo $this->Form->input('contract.accepted_terms', ['label' => 'Cliente aceitou os termos?', 'options' => ['Não', 'Sim']]);
                    echo $this->Form->input('contract.annex', ['label' => 'Link do contrato', 'placeaholder' => 'https://googledrive.com/anaexo']);
                    echo $this->Form->input('username', ['label' => 'Email']);
                    echo $this->Form->input('password', ['label' => 'Senha']);
                    ?>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <?= $this->Form->button(__('Salvar')) ?>
                </div>
                <?= $this->Form->end() ?>
            </div>
        </div>
    </div>
</section>

src/Template/Account/edit.ctp
<?= $this->element('header', [
    'title' => 'Clientes',
    'subtitle' => 'Adicionar'
])
?>

<section class="page-content container-fluid">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card">
                <!-- /.card-header -->
                <!-- form start -->
                <?= $this->Form->create($user, array('role' => 'form')) ?>
                <div class="card-body">
                    <?php
                    echo $this->Form->input('first_name', ['label' => 'Primeiro Nome']);
                    echo $this->Form->input('last_name', ['label' => 'Sobrenome']);

                    echo $this->Form->input('access_admin', ['value' => false, 'type' => 'hidden']);
                    echo $this->Form->input('access_client', ['value' => true, 'type' => 'hidden']);
                    echo $this->Form->input('active', ['value' => true, 'type' => 'hidden']);
                    echo $this->Form->input('contract.accepted_terms', ['label' => 'Cliente aceitou os termos?', 'options' => ['Não', 'Sim']]);
                    echo $this->Form->input('contract.annex', ['label' => 'Link do contrato', 'placeaholder' => 'https://googledrive.com/anaexo']);
                    echo $this->Form->input('username', ['label' => 'Email']);
                    ?>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <?= $this->Form->button(__('Salvar')) ?>
                </div>
                <?= $this->Form->end() ?>
            </div>
        </div>
    </div>
</section>

src/Template/Account/extract.ctp
<?= $this->element('header', [
    'title' => 'Extrato',
    'subtitle' => $user->first_name . ' ' . $user->last_name
])
?>

<section class="page-content container-fluid">
    <div class="row">
        <div class="col-md-9">

            <form class="row" method="get">
                <div class="col-md-3">
                    <select name="year" class="form-control co4">
                        <option value="all" <?= ('all' == $e_year ? 'selected' : '') ?>>Todos
                        </option>
                        <?php for ($i = 2015; $i <= date("Y"); $i++) : ?>
                            <option value="<?= $i ?>" <?= ($i == $e_year ? 'selected' : '') ?>><?= $i ?></option>
                        <?php endfor ?>
                    </select>
                </div>
                <div class="col-md-3">
                    <select class="form-control col-md-" name="month">
                        <option>Escolha o mês</option>
                        <option <?= ('all' == $e_month ? 'selected' : '') ?> value="all">Todos
                        </option>
                        <option <?= (1 == $e_month ? 'selected' : '') ?> value="01">Janeiro
                        </option>
                        <option <?= (2 == $e_month ? 'selected' : '') ?> value="02">Fevereiro
                        </option>
                        <option <?= (3 == $e_month ? 'selected' : '') ?> value="03">Março
                        </option>
                        <option <?= (4 == $e_month ? 'selected' : '') ?> value="04">Abril
                        </option>
                        <option <?= (5 == $e_month ? 'selected' : '') ?> value="05">Maio
                        </option>
                        <option <?= (6 == $e_month ? 'selected' : '') ?> value="06">Junho
                        </option>
                        <option <?= (7 == $e_month ? 'selected' : '') ?> value="07">Julho
                        </option>
                        <option <?= (8 == $e_month ? 'selected' : '') ?> value="08">Agosto
                        </option>
                        <option <?= (9 == $e_month ? 'selected' : '') ?> value="09">Setembro
                        </option>
                        <option <?= (10 == $e_month ? 'selected' : '') ?> value="10">Outubro
                        </option>
                        <option <?= (11 == $e_month ? 'selected' : '') ?> value="11">Novembro
                        </option>
                        <option <?= (12 == $e_month ? 'selected' : '') ?> value="12">Dezembro
                        </option>
                    </select>
                </div>
                <div class="col-md-2">
                    <button type="submit" class="btn btn-primary col-">Alterar</button>
                </div>

            </form>

            <div class="card">
                <!-- /.card-header -->
                <div class="card-body table-responsive no-padding">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th><?= $this->Paginator->sort('real_coin', 'Investimento') ?></th>
                            <th><?= $this->Paginator->sort('date', 'Data') ?></th>
                            <th><?= $this->Paginator->sort('cripto_coin', 'Saldo BTC') ?></th>
                            <th><?= $this->Paginator->sort('dolar_count', 'Cotação BTC Momento da compra/Venda') ?></th>
                            <th><?= $this->Paginator->sort('type', 'Ação') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($extracts as $extract): ?>
                            <tr>
                                <td>R$ <?= $this->Number->format($extract->real_coin) ?></td>
                                <td><?= ($extract->date->format('d/m/Y')) ?></td>
                                <td><?= number_format($extract->cripto_coin, 8) ?></td>
                                <td><?= ($extract->type == 'DEPOSIT') ? 'R$ ' . number_format($extract->cripto_now_price_real, 2, ',', '.') : '$ ' . number_format($extract->cripto_now_price_usd, 2, ',', '.') ?></td>
                                <td><?= $this->Util->badgeType($extract->type) ?></td>

                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
                <div class="card-footer clearfix">
                    <ul class="pagination pagination-sm no-margin pull-right">
                        <?php echo $this->Paginator->numbers(); ?>
                    </ul>
                </div>
            </div>
            <!-- /.box -->
        </div>


        <div class="col-md-3">
            <div class="card">
                <div class="card-body text-center">
                    <h3>
                        <?= number_format($sumExtractBtc->sum, 8, ',', '.') ?>
                    </h3>
                    <strong>BTC</strong>
                </div>
            </div>

            <div class="card">
                <div class="card-body text-center">
                    <h3>
                        R$ <?= number_format($sumExtractReal->sum, 2, ',', '.') ?>
                    </h3>
                    <strong>Investimento</strong>
                </div>
            </div>

            <div class="card">
                <div class="card-body text-center">
                    <h3>
                        <?= number_format($sumExitBtc->sum, 8, ',', '.') ?>
                    </h3>
                    <strong>Retiradas</strong>
                </div>
            </div>

            <div class="card">
                <div class="card-body text-center">
                    <h3>
                        <?= number_format($sumOperationBtc->sum, 8, ',', '.') ?>
                    </h3>
                    <strong>Saldo Operações</strong>
                </div>
            </div>
        </div>

    </div>
</section>
<!-- /.content -->

src/Template/Account/index.ctp
<?= $this->element('header', [
    'title' => 'Clientes',
    'menu' => [
        [
            'title' => 'Clientes',
            'itens' => [
                [
                    'url' => ['action' => 'add'],
                    'icon' => 'plus',
                    'text' => 'Adicionar'
                ]
            ]
        ]
    ]
])
?>

<section class="page-content container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <!-- /.card-header -->
                <div class="card-body table-responsive no-padding">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th><?= $this->Paginator->sort('first_name', 'Nome') ?></th>
                            <th><?= $this->Paginator->sort('username', 'Email') ?></th>
                            <th><?= __('Ações') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($users as $user): ?>
                            <tr>
                                <td><?= h($user->first_name) ?> <?= h($user->last_name) ?></td>
                                <td><?= h($user->username) ?></td>
                                <td>
                                    <?= $this->Html->link(__('Detalhes'), ['action' => 'view', $user->id], ['class' => 'btn btn-info btn-sm']) ?>
                                    <?= $this->Html->link(__('Editar'), ['action' => 'edit', $user->id], ['class' => 'btn btn-warning btn-sm']) ?>
                                    <?= $this->Form->postLink(__('Ativar'), ['action' => 'delete', $user->id], ['confirm' => __('Confirm to delete this entry?'), 'class' => 'btn btn-danger btn-sm']) ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
                <div class="card-footer clearfix">
                    <ul class="pagination pagination-sm no-margin pull-right">
                        <?php echo $this->Paginator->numbers(); ?>
                    </ul>
                </div>
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>
<!-- /.content -->

src/Template/Account/information.ctp
<?= $this->element('header', [
    'title' => 'Cliente',
    'subtitle' => $user->first_name . ' ' . h($user->first_name)
])
?>

<section class="page-content container-fluid">
    <div class="row">
        <div class="col-md-9">
            <div class="card card-solid">
                <div class="card-header with-border">
                    <?php echo __('Informações'); ?>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <dl class="dl-horizontal">
                        <dt><?= __('Nome') ?></dt>
                        <dd>
                            <?= h($user->first_name) ?> <?= h($user->last_name) ?>
                        </dd>
                        <dt><?= __('Email') ?></dt>
                        <dd>
                            <?= h($user->username) ?>
                        </dd>

                        <dt><?= __('Termos aceitos?') ?></dt>
                        <dd>
                            <?php if ($user->contract) {
                                echo ($user->contract->accepted_terms) ? 'Sim' : 'Não';
                            } ?>
                        </dd>


                        <dt><?= __('Contrato Anexo') ?></dt>
                        <dd>
                            <?php if ($user->contract) : ?>
                                <a href="<?= $user->contract->annex ?>" target="_blank">Visualizar </a>
                            <?php endif; ?>
                        </dd>

                    </dl>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- ./col -->
    </div>
    <!-- div -->
</section>

src/Template/Account/login.ctp
<form class="sign-in-form" method="post">
    <div class="card">
        <div class="card-body">
            <a href="/" class="brand text-center d-block m-b-20">
                <img src="/img/logo.png" alt="Trades Logo" width="100">
            </a>
            <div class="form-group">
                <label for="inputEmail" class="sr-only">Email</label>
                <input type="email" id="inputEmail" class="form-control" placeholder="Email" required=""
                       name="username"
                       style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAPhJREFUOBHlU70KgzAQPlMhEvoQTg6OPoOjT+JWOnRqkUKHgqWP4OQbOPokTk6OTkVULNSLVc62oJmbIdzd95NcuGjX2/3YVI/Ts+t0WLE2ut5xsQ0O+90F6UxFjAI8qNcEGONia08e6MNONYwCS7EQAizLmtGUDEzTBNd1fxsYhjEBnHPQNG3KKTYV34F8ec/zwHEciOMYyrIE3/ehKAqIoggo9inGXKmFXwbyBkmSQJqmUNe15IRhCG3byphitm1/eUzDM4qR0TTNjEixGdAnSi3keS5vSk2UDKqqgizLqB4YzvassiKhGtZ/jDMtLOnHz7TE+yf8BaDZXA509yeBAAAAAElFTkSuQmCC&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;">
            </div>

            <div class="form-group">
                <label for="inputPassword" class="sr-only">Senha</label>
                <input type="password" id="inputPassword" class="form-control" placeholder="Senha" required=""
                       name="password"
                       style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAPhJREFUOBHlU70KgzAQPlMhEvoQTg6OPoOjT+JWOnRqkUKHgqWP4OQbOPokTk6OTkVULNSLVc62oJmbIdzd95NcuGjX2/3YVI/Ts+t0WLE2ut5xsQ0O+90F6UxFjAI8qNcEGONia08e6MNONYwCS7EQAizLmtGUDEzTBNd1fxsYhjEBnHPQNG3KKTYV34F8ec/zwHEciOMYyrIE3/ehKAqIoggo9inGXKmFXwbyBkmSQJqmUNe15IRhCG3byphitm1/eUzDM4qR0TTNjEixGdAnSi3keS5vSk2UDKqqgizLqB4YzvassiKhGtZ/jDMtLOnHz7TE+yf8BaDZXA509yeBAAAAAElFTkSuQmCC&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%;">
            </div>
            <div class="checkbox m-b-10 m-t-20">
                <div class="custom-control custom-checkbox checkbox-primary form-check">
                    <input type="checkbox" class="custom-control-input" id="stateCheck1" checked="">
                    <label class="custom-control-label" for="stateCheck1"> Me lembre</label>
                </div>
                <a href="https://account.findup.com.br/users/passwordRecovery" target="_blank" class="float-right">Esqueceu
                    a senha?</a>
            </div>
            <button class="btn btn-primary btn-rounded btn-floating btn-lg btn-block" type="submit">Acessar</button>
            <!--            <p class="text-muted m-t-25 m-b-0 p-0">Don't have an account yet?<a href="auth.register.html"> Create an account</a></p>-->
        </div>

    </div>
</form>